# Server -> Client
VITALS_UPDATE = "VITALS_UPDATE"
ALERT_TRIGGERED = "ALERT_TRIGGERED"
EMERGENCY_START = "EMERGENCY_START"
EMERGENCY_RESOLVE = "EMERGENCY_RESOLVE"
COHORT_CHANGED = "COHORT_CHANGED"
REPLAY_STATUS = "REPLAY_STATUS"
REPLAY_FINISHED = "REPLAY_FINISHED"
BED_CHANGED = "BED_CHANGED"
EQUIPMENT_CHANGED = "EQUIPMENT_CHANGED"

# Client -> Server
CHANGE_SPEED = "CHANGE_SPEED"
SELECT_COHORT = "SELECT_COHORT"
ACKNOWLEDGE_ALERT = "ACKNOWLEDGE_ALERT"
